export const mockUser = {
  uid: 'ponciusz',
  email: 'ponciusz@gmail.com',
};

export const mockData = {
  'users/ponciusz': {
    displayName: 'Kamil Albrycht',
    email: 'ponciusz@gmail.com',
    photoURL: null,
  },
  'users/kowal': {
    displayName: 'Pawel Kownacki',
    email: 'koowal@gmail.com',
    photoURL: null,
  },
  'users/kula': {
    displayName: 'Kula Kulson',
    email: 'kula@gmail.com',
    photoURL: null,
  },
  'users/karni': {
    displayName: 'Karnol Kalrnoliusz',
    email: 'karni@gmail.com',
    photoURL: null,
  },
  'lotteries/ponciusz_a': {
    endDate: '2020-07-11 23:15:41',
    endWhenFull: true,
    maxParticipants: 100,
    name: 'ponciusz_a',
    numberOfWinners: 1,
    owner: 'ponciusz',
    participants: ['koowal', 'kula'],
    prize: 'banan',
    status: 'active',
  },
  'lotteries/ponciusz_b': {
    endDate: '2020-07-11 23:15:41',
    endWhenFull: true,
    maxParticipants: 100,
    name: 'ponciusz_b',
    numberOfWinners: 1,
    owner: 'ponciusz',
    participants: [],
    prize: 'banan',
    status: 'active',
  },
  'lotteries/ponciusz_c': {
    endDate: '2020-07-11 23:15:41',
    endWhenFull: true,
    maxParticipants: 100,
    name: 'ponciusz_c',
    numberOfWinners: 1,
    owner: 'ponciusz',
    participants: ['koowal'],
    prize: 'banan',
    status: 'ended',
  },
  'lotteries/koowal_a': {
    endDate: '2020-07-11 23:15:41',
    endWhenFull: false,
    maxParticipants: 200,
    name: 'koowal_a',
    numberOfWinners: 1,
    owner: 'koowal',
    participants: ['ponciusz'],
    prize: 'super klocki',
    status: 'active',
  },
  'lotteries/koowal_b': {
    endDate: '2020-07-11 23:15:41',
    endWhenFull: false,
    maxParticipants: 200,
    name: 'koowal_b',
    numberOfWinners: 1,
    owner: 'koowal',
    participants: ['kula'],
    prize: 'super klocki',
    status: 'active',
  },
  'lotteries/koowal_c': {
    endDate: '2020-07-11 23:15:41',
    endWhenFull: false,
    maxParticipants: 200,
    name: 'koowal_c',
    numberOfWinners: 1,
    owner: 'koowal',
    participants: ['kula'],
    prize: 'super klocki',
    status: 'active',
  },
};
